packages:
  - 'examples/*'
  - 'packages/*'
  - 'tests'

minimumReleaseAge: 2880 # 2 days in minutes

minimumReleaseAgeExclude:
  - '@appliedblockchain/silentdatarollup-core'
  - '@appliedblockchain/silentdatarollup-custom-rpc'
  - '@appliedblockchain/silentdatarollup-ethers-provider-fireblocks'
  - '@appliedblockchain/silentdatarollup-ethers-provider'
  - '@appliedblockchain/silentdatarollup-hardhat-plugin-fireblocks'
  - '@appliedblockchain/silentdatarollup-hardhat-plugin'
  - '@appliedblockchain/silentdatarollup-hardhat3-plugin'
  - '@appliedblockchain/silentdatarollup-viem-fireblocks'
  - '@appliedblockchain/silentdatarollup-viem'

overrides:
  '@isaacs/brace-expansion': 5.0.1
  '@stablelib/ed25519': 2.1.0
  axios: 1.15.2
  bn.js@^4: 4.12.3
  brace-expansion@^1: 1.1.13
  brace-expansion@^2: 2.0.3
  brace-expansion@^5: 5.0.6
  cookie: 0.7.0
  defu: 6.1.5
  diff: 8.0.3
  fast-uri: 3.1.2
  fflate: 0.8.2
  flatted: 3.4.2
  follow-redirects: 1.16.0
  glob: 10.5.0
  h3: 1.15.9
  handlebars: 4.7.9
  hono: 4.12.23
  immutable@^4: 4.3.8
  jws: 3.2.3
  lodash: 4.18.0
  lodash-es: 4.18.0
  minimatch@<3.1.4: 3.1.4
  minimatch@>=5 <5.1.8: 5.1.8
  minimatch@>=9 <9.0.7: 9.0.7
  minimatch@>=10 <10.2.3: 10.2.3
  path-to-regexp@<0.1.13: 0.1.13
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4 <4.0.4: 4.0.4
  postcss: 8.5.15
  preact: 10.27.3
  qs: 6.15.2
  rollup: 4.59.0
  serialize-javascript: 7.0.5
  socket.io-parser: 4.2.6
  tmp: 0.2.7
  undici: 6.26.0
  uuid: 11.1.1
  vite@^7: 7.3.2
  ws: 8.21.0
