version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1

jobs:
  choose-config:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Pick config
          command: |
            if [ -f .circleci/private-config.yml ]; then
              echo "export CONFIG_PATH=.circleci/private-config.yml" >> "$BASH_ENV"
              echo "Using private-config.yml"
            else
              echo "export CONFIG_PATH=.circleci/public-config.yml" >> "$BASH_ENV"
              echo "Using public-config.yml"
            fi
      - continuation/continue:
          configuration_path: '$CONFIG_PATH'

workflows:
  setup:
    jobs:
      - choose-config
